import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Roy',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Zack',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      _id: 'p1',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Men',
      image: '/images/p1.jpg',
      images: ['/images/p1.jpg', '/images/p2.jpg'],
      price: 120,
      discountPrice: 95,
      countInStock: 10,
      stock: 10,
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Black', 'Navy', 'White'],
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
      material: 'Organic Cotton',
      deliveryEstimate: '2-4 business days',
      isBestSeller: true,
      isNewArrival: true,
      isOnSale: true,
      reviews: [
        {
          name: 'Roy',
          rating: 5,
          comment: 'Perfect fit and premium feel.',
        },
      ],
    },
    {
      _id: 'p2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Women',
      image: '/images/p2.jpg',
      images: ['/images/p2.jpg', '/images/p1.jpg'],
      price: 250,
      discountPrice: 210,
      countInStock: 0,
      stock: 0,
      sizes: ['XS', 'S', 'M'],
      colors: ['Cream', 'Gold'],
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
      material: 'Silk Blend',
      deliveryEstimate: '3-5 business days',
      isBestSeller: false,
      isNewArrival: true,
      isOnSale: true,
      reviews: [
        {
          name: 'Zack',
          rating: 4,
          comment: 'Lovely piece, very stylish.',
        },
      ],
    },
    {
      _id: 'p3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Best Sellers',
      image: '/images/p3.jpg',
      images: ['/images/p3.jpg', '/images/p4.jpg'],
      price: 25,
      discountPrice: 20,
      countInStock: 15,
      stock: 15,
      sizes: ['28', '30', '32', '34'],
      colors: ['Black', 'Olive'],
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
      material: 'Stretch Denim',
      deliveryEstimate: '1-3 business days',
      isBestSeller: true,
      isNewArrival: false,
      isOnSale: true,
      reviews: [
        {
          name: 'Anne',
          rating: 5,
          comment: 'Worth every coin. Fits exactly right.',
        },
      ],
    },
    {
      _id: 'p4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Sale',
      image: '/images/p4.jpg',
      images: ['/images/p4.jpg', '/images/p3.jpg'],
      price: 65,
      discountPrice: 49,
      countInStock: 5,
      stock: 5,
      sizes: ['30', '32', '34', '36'],
      colors: ['Khaki', 'Gray'],
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      material: 'Premium Twill',
      deliveryEstimate: '2-4 business days',
      isBestSeller: false,
      isNewArrival: false,
      isOnSale: true,
      reviews: [
        {
          name: 'James',
          rating: 4,
          comment: 'Great value and clean finish.',
        },
      ],
    },
    {
      _id: 'p5',
      name: 'Urban Kids Hoodie',
      slug: 'urban-kids-hoodie',
      category: 'Kids',
      image: '/images/p1.jpg',
      images: ['/images/p1.jpg', '/images/p2.jpg'],
      price: 55,
      discountPrice: 45,
      countInStock: 12,
      stock: 12,
      sizes: ['6Y', '8Y', '10Y'],
      colors: ['Navy', 'Red'],
      brand: 'Amazona Kids',
      rating: 4.8,
      numReviews: 8,
      description: 'Warm and comfy hoodie for everyday adventures.',
      material: 'Cotton Fleece',
      deliveryEstimate: '2-3 business days',
      isBestSeller: true,
      isNewArrival: true,
      isOnSale: true,
      reviews: [
        {
          name: 'Mary',
          rating: 5,
          comment: 'My son loves it.',
        },
      ],
    },
    {
      _id: 'p6',
      name: 'Luxe Leather Tote',
      slug: 'luxe-leather-tote',
      category: 'Bags',
      image: '/images/p2.jpg',
      images: ['/images/p2.jpg', '/images/p4.jpg'],
      price: 180,
      discountPrice: 0,
      countInStock: 9,
      stock: 9,
      sizes: ['One Size'],
      colors: ['Tan', 'Black'],
      brand: 'Amazona Atelier',
      rating: 4.7,
      numReviews: 16,
      description: 'Elegant tote crafted for modern city life.',
      material: 'Genuine Leather',
      deliveryEstimate: '3-6 business days',
      isBestSeller: true,
      isNewArrival: false,
      isOnSale: false,
      reviews: [
        {
          name: 'Nina',
          rating: 5,
          comment: 'Looks expensive and feels durable.',
        },
      ],
    },
    {
      _id: 'p7',
      name: 'Velocity Runner',
      slug: 'velocity-runner',
      category: 'Shoes',
      image: '/images/p3.jpg',
      images: ['/images/p3.jpg', '/images/p2.jpg'],
      price: 140,
      discountPrice: 119,
      countInStock: 20,
      stock: 20,
      sizes: ['40', '41', '42', '43', '44'],
      colors: ['White', 'Black'],
      brand: 'Amazona Sport',
      rating: 4.6,
      numReviews: 22,
      description: 'Lightweight premium runners for all-day comfort.',
      material: 'Mesh + Rubber',
      deliveryEstimate: '1-2 business days',
      isBestSeller: true,
      isNewArrival: true,
      isOnSale: true,
      reviews: [
        {
          name: 'Kai',
          rating: 5,
          comment: 'Super comfortable right out of the box.',
        },
      ],
    },
    {
      _id: 'p8',
      name: 'Runway Trench Coat',
      slug: 'runway-trench-coat',
      category: 'New Arrivals',
      image: '/images/p4.jpg',
      images: ['/images/p4.jpg', '/images/p1.jpg'],
      price: 320,
      discountPrice: 280,
      countInStock: 7,
      stock: 7,
      sizes: ['S', 'M', 'L'],
      colors: ['Camel', 'Ivory'],
      brand: 'Amazona Couture',
      rating: 4.9,
      numReviews: 6,
      description: 'Statement trench coat with tailored silhouette.',
      material: 'Wool Blend',
      deliveryEstimate: '3-5 business days',
      isBestSeller: false,
      isNewArrival: true,
      isOnSale: true,
      reviews: [
        {
          name: 'Lena',
          rating: 5,
          comment: 'Absolute luxury look.',
        },
      ],
    },
  ],
};
export default data;
